[project]
title = "Superstore Analysis Dashboard"
version = "0.1.0"
port = 8502
slug = "my-first-preswald-app-540052"  
entrypoint = "hello.py"    

[branding]
name = "Superstore Analysis Dashboard"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.my_sample_superstore]
type = "csv"
path = "data/my_sample_superstore.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"