[project]
title = "Emerging Architectures for LLM Applications 2025"
version = "0.1.0"
port = 8502
slug = "llm-architectures-2025"  
entrypoint = "hello.py"    

[branding]
name = "LLM Architecture Analysis"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#3B82F6"  # Blue color matching the diagrams

[data.architectures_pdf]
type = "pdf"
path = "Emerging Architectures for LLM Applications _ Andreessen Horowitz.pdf"

[data.architectures_html]
type = "html"
path = "Emerging Architectures for LLM Applications 2025.html"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"