[project]
title = "Preswald Project"
version = "0.1.0"
port = 8504
slug = "my-project-553106"  
entrypoint = "hello.py"    

[branding]
name = "Superstore Story"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.my_sample_superstore]
type = "csv"
path = "data/my_sample_superstore.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"