[project]
title = "Preswald Project"
version = "0.1.0"
port = 8505
slug = "my-project-129470"  
entrypoint = "hello.py"    

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data]
my_sample_superstore = { type = "csv", path = "data/my_sample_superstore.csv" }

[logging]
level = "DEBUG"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"